apiVersion: v1
kind: Config
clusters:
  - name: minikube
    cluster:
      server: https://127.0.0.1:8443
      certificate-authority: /home/user/.minikube/ca.crt
contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
current-context: minikube
users:
  - name: minikube
    user:
      client-certificate: /home/user/.minikube/client.crt
      client-key: /home/user/.minikube/client.key